name: citgroupvn_ecommerce_delivery
description: A new Flutter application.
publish_to: 'none' #
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.1
  shared_preferences: ^2.0.6
  connectivity: ^3.0.6
  firebase_core: ^2.4.1
  firebase_messaging: ^14.2.1
  flutter_local_notifications: ^17.0.0
  path_provider: ^2.0.10
  url_strategy: ^0.2.0
  pin_code_fields: ^8.0.1
  http: ^0.13.1
  flutter_switch: ^0.3.2
  shimmer_animation: ^2.0.0
  geolocator: ^11.0.0
  geocoding: ^3.0.0
  google_maps_flutter: ^2.0.6
  url_launcher: ^6.1.2
  vibration: ^1.7.6
  image_picker: ^1.0.7
  disable_battery_optimization: ^1.1.0+1
  phone_number: ^2.1.0
  country_code_picker: ^2.0.2
#  location: ^4.4.0
  audioplayers: ^0.20.1
  flutter_html: ^3.0.0-alpha.5
  cached_network_image: ^3.2.3
  image_compression_flutter: ^1.0.2
  win32: ^5.3.0
  path: ^1.8.1
  http_parser: ^4.0.2
  intl: ^0.19.0
  dotted_border: ^2.0.0+1
  photo_view: ^0.14.0
  web_socket_channel: ^2.4.0

dependency_overrides:
  modal_bottom_sheet: ^3.0.0-pre

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/image/
    - assets/language/
    - assets/notification.mp3

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/font/Roboto-Regular.ttf
          weight: 400
        - asset: assets/font/Roboto-Medium.ttf
          weight: 500
        - asset: assets/font/Roboto-Bold.ttf
          weight: 700
        - asset: assets/font/Roboto-Black.ttf
          weight: 900