name: citgroupvn_ecommerce_store
description: An application for multivendor ecommerce restaurant.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.1
  shared_preferences: ^2.0.6
  connectivity: ^3.0.6
  firebase_core: ^2.4.1
  firebase_messaging: ^14.2.1
  flutter_local_notifications: ^13.0.0
  path_provider: ^2.0.2
  url_strategy: ^0.2.0
  shimmer_animation: ^2.0.0
  image_picker: ^0.8.0+4
  http: ^0.13.3
  pin_code_fields: ^7.2.0
  url_launcher: ^6.1.2
  vibration: ^1.7.6
  audioplayers: ^0.20.1
  flutter_switch: ^0.3.2
  flutter_typeahead: ^4.3.7
  phone_number: ^1.0.0
  country_code_picker: ^2.0.2
  flutter_html: ^3.0.0-alpha.6
  bluetooth_thermal_printer: ^0.0.6
  photo_view: ^0.14.0
  image_compression_flutter: ^1.0.2
  win32: ^3.1.3
  google_maps_flutter: ^2.1.1
  geolocator: ^9.0.2
  cached_network_image: ^3.2.1
  flutter_pos_printer_platform: ^1.1.0
  esc_pos_utils: ^1.1.0
  screenshot: ^2.1.0
  http_parser: ^4.0.2
  path: ^1.8.1
  intl: ^0.18.0
  image: ^3.0.2
  dotted_border: ^2.0.0+1
  carousel_slider: ^4.0.0
  just_the_tooltip: ^0.0.12

dependency_overrides:
  modal_bottom_sheet: ^3.0.0-pre

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/image/
    - assets/language/
    - assets/notification.mp3

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/font/Roboto-Regular.ttf
          weight: 400
        - asset: assets/font/Roboto-Medium.ttf
          weight: 500
        - asset: assets/font/Roboto-Bold.ttf
          weight: 700
        - asset: assets/font/Roboto-Black.ttf
          weight: 900